id: P009629
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG24033
  title: རོ་མེའོ་དང་ཇུ་ལིཀྲི།
  author: ''
  volumes:
    59f17b43f6524237b9fba264dea78abe:
      image_group_id: I1KG24180
      title: ''
      volume_number: 1
      total_pages: 334
