id: IC31B8559
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T04:18:46+00:00'
last_modified: '2022-06-08T12:23:07.240349+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG24033
  title: རོ་མེའོ་དང་ཇུ་ལིཀྲི།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    10BC:
      image_group_id: I1KG24180
      title: ''
      total_pages: 334
      order: 1
      base_file: 10BC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
